version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - N8N_WEBHOOK_URL=http://n8n:5678/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    depends_on:
      - n8n
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your-secret-encryption-key}
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=${N8N_SMTP_HOST:-smtp.example.com}
      - N8N_SMTP_PORT=${N8N_SMTP_PORT:-587}
      - N8N_SMTP_USER=${N8N_SMTP_USER:-user@example.com}
      - N8N_SMTP_PASS=${N8N_SMTP_PASS:-your-email-password}
      - N8N_SMTP_SENDER=${N8N_SMTP_SENDER:-n8n@example.com}
      - N8N_SMTP_SSL_TLS=${N8N_SMTP_SSL_TLS:-true}
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data: