"""Add VolunteerAnalysis model

Revision ID: d2109c0b85e9
Revises: 
Create Date: 2025-07-29 18:18:52.296893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2109c0b85e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voluntario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=False),
    sa.Column('resultado', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voluntario_id'], ['Voluntarios.voluntarios_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_analysis_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_analysis_id'))

    op.drop_table('volunteer_analysis')
    # ### end Alembic commands ###
